package com.example.utils

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.data.CarbonActivity
import com.example.data.User
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfExporter {
    fun generateAndShareReport(
        context: Context,
        user: User,
        activities: List<CarbonActivity>,
        monthlyEmissions: Double,
        monthlyGoal: Double
    ) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val paint = Paint()
        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 12f
            isAntiAlias = true
        }
        val titlePaint = Paint().apply {
            color = Color.parseColor("#2E7D32") // Eco Green
            textSize = 24f
            isFakeBoldText = true
            isAntiAlias = true
        }
        val headerPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 14f
            isFakeBoldText = true
            isAntiAlias = true
        }

        // Draw header
        canvas.drawText("EcoImpact Tracker", 40f, 60f, titlePaint)
        
        val dateStr = SimpleDateFormat("MMMM yyyy", Locale.getDefault()).format(Date())
        canvas.drawText("Monthly Carbon Footprint Report - $dateStr", 40f, 90f, headerPaint)
        
        // Draw user info
        textPaint.textSize = 12f
        canvas.drawText("User Name: ${user.name}", 40f, 130f, textPaint)
        canvas.drawText("Email: ${user.email}", 40f, 150f, textPaint)
        canvas.drawText("Monthly Carbon Budget: ${String.format("%.1f", monthlyGoal)} kg CO2", 40f, 170f, textPaint)
        canvas.drawText("Total Emissions Logged: ${String.format("%.1f", monthlyEmissions)} kg CO2", 40f, 190f, textPaint)
        
        val status = if (monthlyEmissions <= monthlyGoal) "Under Budget (Excellent!)" else "Over Budget (Needs Action)"
        canvas.drawText("Budget Status: $status", 40f, 210f, textPaint)

        // Draw Table Header
        canvas.drawText("Logged Activities Summary", 40f, 260f, headerPaint)
        paint.color = Color.parseColor("#4CAF50")
        canvas.drawRect(40f, 275f, 555f, 280f, paint)

        var y = 300f
        canvas.drawText("Category", 45f, y, textPaint)
        canvas.drawText("Subtype", 160f, y, textPaint)
        canvas.drawText("Value", 300f, y, textPaint)
        canvas.drawText("Emissions (kg CO2)", 420f, y, textPaint)

        paint.color = Color.LTGRAY
        canvas.drawRect(40f, y + 5, 555f, y + 6, paint)

        y += 25f
        activities.take(15).forEach { activity ->
            if (y > 800) return@forEach
            canvas.drawText(activity.category, 45f, y, textPaint)
            canvas.drawText(activity.subType, 160f, y, textPaint)
            canvas.drawText("${activity.value}", 300f, y, textPaint)
            canvas.drawText(String.format("%.1f", activity.co2Emissions), 420f, y, textPaint)
            y += 20f
        }

        // Draw footer
        paint.color = Color.parseColor("#2E7D32")
        canvas.drawRect(40f, 810f, 555f, 812f, paint)
        textPaint.textSize = 9f
        textPaint.color = Color.GRAY
        canvas.drawText("Generated by EcoImpact Tracker - Thank you for caring for our planet!", 40f, 825f, textPaint)

        pdfDocument.finishPage(page)

        try {
            val cachePath = File(context.cacheDir, "reports")
            cachePath.mkdirs()
            val file = File(cachePath, "EcoImpact_Report_${System.currentTimeMillis()}.pdf")
            val outputStream = FileOutputStream(file)
            pdfDocument.writeTo(outputStream)
            outputStream.close()

            val uri = FileProvider.getUriForFile(context, "com.aistudio.ecoimpact.tracker.fileprovider", file)
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "EcoImpact Carbon Footprint Report")
                putExtra(Intent.EXTRA_TEXT, "Here is my carbon footprint report for this month generated using EcoImpact Tracker!")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(Intent.createChooser(intent, "Share Report PDF"))
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            pdfDocument.close()
        }
    }
}
